spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - protocol: TCP
      name: "9990"
      port: 9990
      targetPort: 9990
      nodePort: 32001
